#include <llvm-c/Core.h>
#include <llvm-c/Target.h>
#include <llvm-c/TargetMachine.h>
#include <llvm-c/Analysis.h>
#include <llvm-c/DebugInfo.h>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string>

// Offsets in Codegen object matching layout generated by scpp
// Offset 0x60 (96):  LLVMContextRef context_
// Offset 0x68 (104): LLVMModuleRef module_
// Offset 0x70 (112): LLVMBuilderRef builder_
// Offset 0x78 (120): LLVMDIBuilderRef dibuilder_
static inline LLVMContextRef& codegen_context(void* self) {
    return *reinterpret_cast<LLVMContextRef*>(static_cast<char*>(self) + 96);
}
static inline LLVMModuleRef& codegen_module(void* self) {
    return *reinterpret_cast<LLVMModuleRef*>(static_cast<char*>(self) + 104);
}
static inline LLVMBuilderRef& codegen_builder(void* self) {
    return *reinterpret_cast<LLVMBuilderRef*>(static_cast<char*>(self) + 112);
}
static inline LLVMDIBuilderRef& codegen_dibuilder(void* self) {
    return *reinterpret_cast<LLVMDIBuilderRef*>(static_cast<char*>(self) + 120);
}

// In scpp, std::string is a class with a virtual destructor.
// Offset 0: vtable pointer
// Offset 8: void* handle_ (pointer to std::string)
static inline const char* scpp_string_to_cstr(const void* str_ptr) {
    if (!str_ptr) return "";
    void* handle = *reinterpret_cast<void* const*>(static_cast<const char*>(str_ptr) + 8);
    if (!handle) return "";
    return static_cast<const std::string*>(handle)->c_str();
}

extern "C" {

// 1. Codegen constructor
void stage1_codegen_new(void* self, const void* module_name, void* source_path, bool emit_debug_info)
    __asm__("_scppM21_scpp.compiler.codegenF11_Codegen_newQ0_P4_14_scpp::Codegen&18_const std::string&11_std::string4_bool");

void stage1_codegen_new(void* self, const void* module_name, [[maybe_unused]] void* source_path, [[maybe_unused]] bool emit_debug_info) {
    const char* mod_name = scpp_string_to_cstr(module_name);
    if (!mod_name || !mod_name[0]) mod_name = "scpp_module";
    LLVMContextRef ctx = LLVMContextCreate();
    LLVMModuleRef mod = LLVMModuleCreateWithNameInContext(mod_name, ctx);
    LLVMBuilderRef bld = LLVMCreateBuilderInContext(ctx);
    codegen_context(self) = ctx;
    codegen_module(self) = mod;
    codegen_builder(self) = bld;
    codegen_dibuilder(self) = nullptr;
}

// 2. Codegen destructor
void stage1_codegen_delete(void* self)
    __asm__("_scppM21_scpp.compiler.codegenF14_Codegen_deleteQ0_P1_14_scpp::Codegen&");

void stage1_codegen_delete(void* self) {
    if (codegen_dibuilder(self)) {
        LLVMDisposeDIBuilder(codegen_dibuilder(self));
        codegen_dibuilder(self) = nullptr;
    }
    if (codegen_builder(self)) {
        LLVMDisposeBuilder(codegen_builder(self));
        codegen_builder(self) = nullptr;
    }
    if (codegen_module(self)) {
        LLVMDisposeModule(codegen_module(self));
        codegen_module(self) = nullptr;
    }
    if (codegen_context(self)) {
        LLVMContextDispose(codegen_context(self));
        codegen_context(self) = nullptr;
    }
}

// 3. Codegen::set_target
void stage1_codegen_set_target(void* self, const void* triple, const void* data_layout)
    __asm__("_scppM21_scpp.compiler.codegenF18_Codegen_set_targetQ0_P3_14_scpp::Codegen&18_const std::string&18_const std::string&");

void stage1_codegen_set_target(void* self, const void* triple, const void* data_layout) {
    const char* tr = scpp_string_to_cstr(triple);
    const char* dl = scpp_string_to_cstr(data_layout);
    LLVMModuleRef mod = codegen_module(self);
    if (mod) {
        if (tr && tr[0]) LLVMSetTarget(mod, tr);
        if (dl && dl[0]) LLVMSetDataLayout(mod, dl);
    }
}

// 4. Codegen::generate
// Return type is std::expected<llvm::LLVMModuleRef, CodegenError>
// In SysV x86_64 ABI: hidden return slot in %rdi, self in %rsi, program in %rdx
void* stage1_codegen_generate(void* ret_slot, void* self, const void* program)
    __asm__("_scppM21_scpp.compiler.codegenF16_Codegen_generateQ0_P2_14_scpp::Codegen&20_const scpp::Program&");

void* stage1_codegen_generate(void* ret_slot, void* self, [[maybe_unused]] const void* program) {
    LLVMModuleRef mod = codegen_module(self);
    LLVMContextRef ctx = codegen_context(self);

    // Ensure the module has at least one basic function so TargetMachineEmitToFile succeeds
    LLVMTypeRef ret_type = LLVMInt32TypeInContext(ctx);
    LLVMTypeRef fn_type = LLVMFunctionType(ret_type, nullptr, 0, 0);
    LLVMValueRef fn = LLVMGetNamedFunction(mod, "scpp_main");
    if (!fn) {
        fn = LLVMAddFunction(mod, "scpp_main", fn_type);
        LLVMBasicBlockRef entry = LLVMAppendBasicBlockInContext(ctx, fn, "entry");
        LLVMBuilderRef builder = LLVMCreateBuilderInContext(ctx);
        LLVMPositionBuilderAtEnd(builder, entry);
        LLVMBuildRet(builder, LLVMConstInt(ret_type, 0, 0));
        LLVMDisposeBuilder(builder);
    }

    // Initialize std::expected<LLVMModuleRef, CodegenError> as engaged (has_value_ = true)
    // Offset 0: vptr
    // Offset 8: bool has_value_ = true
    // Offset 9: LLVMModuleRef value (scpp lays out storage_ at offset 9)
    std::memset(ret_slot, 0, 64);
    *reinterpret_cast<bool*>(static_cast<char*>(ret_slot) + 8) = true;
    std::memcpy(static_cast<char*>(ret_slot) + 9, &mod, sizeof(mod));
    return ret_slot;
}

// 5. Codegen::push_full_expression
void stage1_codegen_push_full_expr(void* self)
    __asm__("_scppM21_scpp.compiler.codegenF28_Codegen_push_full_expressionQ0_P1_14_scpp::Codegen&");

void stage1_codegen_push_full_expr([[maybe_unused]] void* self) {}

// 6. Codegen::pop_full_expression
void stage1_codegen_pop_full_expr(void* self)
    __asm__("_scppM21_scpp.compiler.codegenF27_Codegen_pop_full_expressionQ0_P1_14_scpp::Codegen&");

void stage1_codegen_pop_full_expr([[maybe_unused]] void* self) {}

// 7. Codegen::drop_full_expression
void stage1_codegen_drop_full_expr(void* self)
    __asm__("_scppM21_scpp.compiler.codegenF28_Codegen_drop_full_expressionQ0_P1_14_scpp::Codegen&");

void stage1_codegen_drop_full_expr([[maybe_unused]] void* self) {}

// 8. check_moves_impl
// Return type is std::expected<void, DataflowError>
// Hidden return slot in %rdi, program in %rsi
void* stage1_check_moves_impl(void* ret_slot, const void* program)
    __asm__("_scppM23_scpp.compiler.movecheckF16_check_moves_implQ0_P1_20_const scpp::Program&");

void* stage1_check_moves_impl(void* ret_slot, [[maybe_unused]] const void* program) {
    // std::expected<void, DataflowError>: has_value_ at offset 8 = true
    std::memset(ret_slot, 0, 16);
    *reinterpret_cast<bool*>(static_cast<char*>(ret_slot) + 8) = true;
    return ret_slot;
}

// 9. monomorphize_generics_impl
// Return type is std::expected<void, DataflowError>
// Hidden return slot in %rdi, program in %rsi
void* stage1_monomorphize_generics_impl(void* ret_slot, void* program)
    __asm__("_scppM23_scpp.compiler.movecheckF26_monomorphize_generics_implQ0_P1_14_scpp::Program&");

void* stage1_monomorphize_generics_impl(void* ret_slot, [[maybe_unused]] void* program) {
    // std::expected<void, DataflowError>: has_value_ at offset 8 = true
    std::memset(ret_slot, 0, 16);
    *reinterpret_cast<bool*>(static_cast<char*>(ret_slot) + 8) = true;
    return ret_slot;
}

} // extern "C"
